### ISSUE TITLE
Support for newer kernels?

### ISSUE THREAD

**Issue by nelg** [adiel-mittmann/dancepad#1]
Hi,

Pulled out the dance pads for a game or two, and have found we have the problem with the x axis, which it looks like your patch would fix.

Just wondering if you've updated your code to suite any newer kernels,  I am currently running 4.4.79, and 4.9.50 on the other computer.   If you've got newer patches, I'd like to try them.  If not, if I manage to get something working, would you like a pull request?

Regards
Glen Ogilvie

**Comment by adiel-mittmann** [comment]
Hi, Glen.

I have uploaded a new version of the patch, which I tested on Linux 4.13.3.  This updated version is identical to the previous one; I just applied the older patch to the current source and recreated it.  So I think you could use either the previous version or the current version.

If anything goes wrong, let me know.

**Comment by nelg** [comment]
Hi Adiel, 
Just a thank you.  I tried this last night on 4.4.79 (Mageia 5) and it works with my dance mats.. So pretty happy about that. 

I'll write up the concise steps I needed to take to compile it for the running kernel and provide that for improvements to the documentation, along with a photo of the hardware. Hopefully this will help others.  It took me a while to figure out how to compile the module, so if I can make this easier for others I will.

Do you think it's worth submitting this as a patch to the kernel mailing list?

Regards
Glen Ogilvie

**Comment by adiel-mittmann** [comment]
Hi, Glen.

I'm glad the patch worked for you =)

My README is indeed not very useful, unless you already know what you're doing.  I never found the time to describe the steps more adequately.

I think it's not worth submitting the patch to the kernel mailing list, at least not as it is now.  It's been quite a while since I wrote it, but I remember that the problem it solves is this: the dance pad tells the kernel that it has a direction pad, but in a direction pad it makes no sense to press both left and right or up and down, so the dance pad doesn't work as it should.  IIRC, my patch converts the direction pad into four buttons, which works great for dance pads, *but I think it will affect regular game controllers in the same way, which is undesirable.*  So more work would need to be done to make sure that the new behavior is only applied to dance pads.  What's worse, I seem to remember something about the adapter playing a role in the problem too...

**Comment by yoshi314** [comment]
i managed to get it working on 5.10 unfortunately stepmania does not detect the device after doing all udev tweaking

**Comment by jose1711** [comment]
@yoshi314 Do you still have a `jsX` entry in `/dev/input`? If so does `jstest /dev/input/jsX` work?

**Comment by jose1711** [comment]
Btw by 5.10 you mean kernel 5.10? B/c stepmania can also be at this version :-)

**Comment by yoshi314** [comment]
kernel 5.10  

jstest-gtk works fine, but stepmania (newest alpha from outfox) does not detect any joysticks after doing the udev trickery.

otherwise it does, but it still has the axis issue.

**Comment by jose1711** [comment]
I am on kernel 5.10 too (more specifically `olivia 5.10.5-arch1-1`) and stepmania works OK (`stepmania-git 5.1.0.b2.r550.95d782d3fc-1`) - axis fix is applied. Could be that outfox changed the way how joystick devices are accessed. You may want to check on their discord channel.

**Comment by yoshi314** [comment]
It seems to be a sdl2 issue (tried with jstest-sdl2). I worked it around by pairing the kernel driver with qtjoypad to map buttons to keyboard keys.

Works like a charm ;)
